using Tnf.Zero.Application;
using Tnf.Zero.EntityFrameworkCore;
using System;
using Tnf.App.AspNetCore.TestBase;
using Tnf.App.EntityFrameworkCore;
using Tnf.Modules;

namespace Tnf.Zero.Web.Tests.App
{
    [DependsOn(
        typeof(AppModule),
        typeof(TnfAppAspNetCoreTestBaseModule))]
    public class AppTestModule : TnfModule
    {
        public override void PreInitialize()
        {
            base.PreInitialize();

            Configuration
                .TnfEfCoreInMemory(IocManager.Resolve<IServiceProvider>())
                // The Context can be generated by the Crudzilla Tool
                .RegisterDbContextInMemory<TnfZeroContext>();
        }

        public override void Initialize()
        {
            base.Initialize();

            // Register all the interfaces and its implmentations on this assembly
            IocManager.RegisterAssemblyByConvention<AppTestModule>();
        }
    }
}
