using Microsoft.EntityFrameworkCore;
using Tnf.App.EntityFrameworkCore;
using Tnf.EntityFrameworkCore.Configuration;
using Tnf.Modules;

namespace Tnf.Zero.EntityFrameworkCore
{
    [DependsOn(
        typeof(TnfAppEntityFrameworkCoreModule))]
    public class EntityFrameworkModule : TnfModule
    {
        public override void PreInitialize()
        {
            base.PreInitialize();

            Configuration
                .Modules
                .TnfEfCore()
                // The Context can be generated by the Crudzilla Tool
                .AddDbContext<TnfZeroContext>(configuration =>
                {
                    configuration.DbContextOptions.UseSqlServer(configuration.ConnectionString);
                });
        }

        public override void Initialize()
        {
            base.Initialize();

            // Register all the interfaces and its implmentations on this assembly
            IocManager.RegisterAssemblyByConvention<EntityFrameworkModule>();
        }
    }
}